### ISSUE TITLE
El nombre del ejecutable ha cambiado a telegram.exe

### ISSUE THREAD

**Issue by sukiletxe** [GerardKessler/Unigram#2]
Esto significa que el módulo de aplicación deja de funcionar. Hay que seguir [la sección 3.4 de la guía de desarrolladores](https://www.nvaccess.org/files/nvda/documentation/developerGuide.html#AssociatingAppModule) (donde ya dan un código para que se adapte cambiando tres cadenas) para asociar el complemento unigram con el ejecutable telegram.exe. (Alternativamente, se puede simplemente cambiar el nombre de la carpeta unigram a telegram y funcionará igual). El plugin global umStart sigue funcionando con cualquiera de estos dos cambios (y juraría que sin hacerlos también).

**Comment by ghost** [comment]
Hola. Muchas gracias por el aviso. Por acá todavía no ha llegado ese cambio, por lo que voy a esperar un poco para lanzar la release. El repositorio ya tiene renombrada la carpeta del módulo así como las rutas del buildVars.
