### ISSUE TITLE
Unigram addon for NVDA isn't compatible

### ISSUE THREAD

**Issue by Giovani93** [GerardKessler/Unigram#4]
Hello.
Unigram addon for NVDA isn't compatible with newest version of this add-on. Please, could You rewrite this add-on to be compatible?
Thank You.
Marco Oros

**Comment by ghost** [comment]
Hola. He dejado de desarrollar este complemento debido a la existencia de otro proyecto, Unigram plus, para evitar esfuerzos paralelos para un mismo fin. En la comunidad hispana hay subida una versión aún funcional de mi complemento. Si el autor del plus sigue sin actualizar el suyo, intentaré volver a desarrollar este.
<https://nvda.es/files/get.php?file=unigram>
